name: fido2
description: FIDO2 (CTAP2) library for dart
version: 0.0.1
repository: https://github.com/nfcim/fido2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cbor: ^6.1.1
  convert: ^3.0.1
  cryptography: ^2.7.0
  elliptic: ^0.3.10
  quiver: ^3.2.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
